### ISSUE TITLE
The number of TEs in mammals in dfam38'full.0.h5.gz is less than what is displayed on the official website

### ISSUE THREAD

**Issue by limengyang9797** [Dfam-consortium/FamDB#10]
Hello! I downloaded the dfam38_full.0.h5.gz file from Dfam (https://dfam.org/releases/Dfam_3.8/families/FamDB/) and configured it in RepeatMasker-4.1.6 software. Subsequently, I used famdb.py and buildRMLibFromEMBL.pl programs to extract mammalian TE sequences from the dfam38_full.0.h5 file, and found that there were only over 1000 TEs. This does not match the 10,778 TEs of mammals that I searched on the official website page (https://dfam.org/browse?clade=40674&clade_descendants=true). 
Therefore, I would like to know where this issue lies and whether there are any other partition files containing TEs from mammals.

Here are the commands I ran:
famdb.py -i /home/RepeatMasker/Libraries/famdb/ families -f embl -d Mammalia > Mammalia_TE.embl
buildRMLibFromEMBL.pl Mammalia_TE.embl > Mammalia_TE.fasta

**Comment by asgray** [comment]
Hi, can you describe what you did when you said you configured the file in RepeatMasker? Are you intending to run RepeatMasker, or do you just want a fasta file of the Mammalian TE families?

Your commands look correct to me, and when I run them I get the numbers I expect. The root partition (#0) should contain Mammalia and all descendant taxa as well, so I'm not sure what's going wrong. Just as a sanity check, try running this:
`famdb.py -i <path to your installation folder> info`
My output, when only file 0 is present, looks like:
```
FamDB Directory     : /blahblahblah
FamDB Generator     : famdb.py v1.0
FamDB Format Version: 1.0
FamDB Creation Date : 2023-11-15 11:30:15.311827

Database: Dfam
Version : 3.8
Date    : 2023-11-14

Dfam - A database of transposable element (TE) sequence alignments and HMMs.

1 Partitions Present
Total consensus sequences present: 295552
Total HMMs present               : 295552


Partition Details
-----------------
 Partition 0 [dfam38_full.0.h5]: root - Mammalia, Amoebozoa, Bacteria <bacteria>, Choanoflagellata, Rhodophyta, Haptista, Metamonada, Fungi, Sar, Placozoa, Ctenophora <comb jellies>, Filasterea, Spiralia, Discoba, Cnidaria, Porifera, Viruses
     Consensi: 295552, HMMs: 295552

 Partition 1 [ Absent ]: Obtectomera 
 ...
```
 
One thing to note is that if you are looking for the 10,778 mammal families, you should use the `--curated` flag as well, but omitting it should give you more hits, not less.

**Comment by limengyang9797** [comment]
Thank you for your reply. I want to obtain the fasta file of the mammalian TE families from the dfam38 database. When I run: `famdb.py -i /home/mengyang/app/RepeatMasker/Libraries/famdb/ info`
The results are as follows:
```
FamDB Directory     : /home/mengyang/app/RepeatMasker/Libraries/famdb
FamDB Generator     : famdb.py v1.0
FamDB Format Version: 1.0
FamDB Creation Date : 2023-11-15 11:30:15.311827

Database: Dfam withRBRM
Version : 3.8
Date    : 2023-11-14

Dfam - A database of transposable element (TE) sequence alignments and HMMs.
RBRM - RepBase RepeatMasker Edition - version 20181026

1 Partitions Present
Total consensus sequences present: 308177
Total HMMs present               : 295552


Partition Details
-----------------
 Partition 0 [dfam38_full.0.h5]: root - Mammalia, Amoebozoa, Bacteria <bacteria>, Choanoflagellata, Rhodophyta, Haptista, Metamonada, Fungi, Sar, Placozoa, Ctenophora <comb jellies>, Filasterea, Spiralia, Discoba, Cnidaria, Porifera, Viruses
     Consensi: 308177, HMMs: 295552

 Partition 1 [ Absent ]: Obtectomera
```
The extra consensus sequences number may be due to I added the Repbase database using the addRepBase.pl script. There seems to be no problem elsewhere. I tried again to extract mammalian TE sequences from dfam38, but the result was still only over 1,000.

In addition, I tried RepeatMasker-4.1.5 and its built-in dfam37 database, and found that there are over 10,000 TE families in mammals, which is normal.

**Comment by asgray** [comment]
If all you need is the fasta file, FamDB should be able to produce it in one step:
`famdb.py -i ./dfam38 families -f fasta_acc -d --curated Mammalia > Mammalia.fasta`
I tested mine with:
```
agray@repeatmasker:~/projects/Dfam-umbrella/FamDB$ grep -c ">" Mammalia.fasta 
10778
```

That said, there is definitely a bug in `buildRMLibFromEMBL.pl`, so thanks for calling attention to it, it's being updated now.

I've also been unable to replicate your error, and I'm struggling to think of a reason why your file is returning so few hits. If the above command doesn't produce the correct number of hits, try running:
`famdb.py -i /home/mengyang/app/RepeatMasker/Libraries/famdb/ lineage -d --curated mammalia > Mammalia.lineage`

The output file will show the family count for each taxa in the query, you can do a `diff` comparison to this file to see what information is missing:
[Mammalia_RMRB_cur.lineage.txt](https://github.com/user-attachments/files/15828345/Mammalia_RMRB_cur.lineage.txt)

If none of that works, send us an email at help@dfam.org and we can send you the fasta file and/or give you a link to upload your .h5 file to diagnose the issue(s).

**Comment by limengyang9797** [comment]
I ran the following command：
`famdb.py -i /home/mengyang/app/RepeatMasker/Libraries/famdb/ families --include-class-in-name -f fasta_acc -d --curated Mammalia > Mammalia.fasta`
```
grep -c ">" Mammalia.fasta
14549
```
I am glad that this command is effective. Thank you very much for your patient reply.

**Comment by limengyang9797** [comment]
I think there may be an issue with the `-f embl` parameter of `famdb.py` I installed, while `-f fasta_cc` and `-f embl_seq` are correct.
