### ISSUE TITLE
Famdb.py incompatibility with Dfam 3.8

### ISSUE THREAD

**Issue by mbeavitt** [Dfam-consortium/FamDB#11]
Not sure the best way to go about this, but I discovered a bug in the famdb.py python script that came packaged with repeatmasker, as well as proposing a fix. I figure it's probably best to post here too, since this is the correct repo for the tool!

Original issue on repeatmasker repo:
https://github.com/rmhubley/RepeatMasker/issues/268

Proposed fix:
https://github.com/rmhubley/RepeatMasker/pull/269

**Comment by asgray** [comment]
Fix accepted
