### ISSUE TITLE
FamDB Format 1.0 Partitions: is there a way to get only curated?

### ISSUE THREAD

**Issue by minhasbushra** [Dfam-consortium/FamDB#13]
Hi, 

I am trying to get FamDB partitions for Repeat Masker. Is there a way to get only curated families using the partitions? 

Thanks
Bushra

**Comment by asgray** [comment]
Hi Bushra, you can get the curated families from FamDB files with the `families` command and the `--curated` flag. For example,
`python3 famdb.py -i ~/<installation path>/ families -d --curated --format fasta_acc <term> > out.fasta`
would output the curated families from <term> and all descendant taxa to a fasta file. 
More format and filtering options are accessible with the `families -h` command as well. 

Note that you will need the partition files for all of your species of interest. 

If you want all of the curated families in Dfam, regardless of species, the `RepeatMasker.lib` file packaged with RepeatMasker contains them all in fasta format.
