### ISSUE TITLE
ERROR:__main__:Error reading file: This file cannot be read by this version of famdb.py.

### ISSUE THREAD

**Issue by AntonioBaeza** [Dfam-consortium/FamDB#3]
Singularity> ls
Dfam.h5  Dfam.h5.gz  config.ini  dnapipete.img  famdb.py
Singularity>
Singularity> famdb.py -i Dfam.h5 families -f fasta_name -a Panarthropoda  --include-class-in-name > library.fasta
ERROR:__main__:Error reading file: This file cannot be read by this version of famdb.py.
Singularity>

Any comment on how to proceed?
I tried the script with the last available Dfam database
thanks

**Comment by clemgoub** [comment]
Hello!

It is likely the issue is caused when `famdb` is used within the Singularity image of `dnaPipeTE`.
See [here](https://github.com/clemgoub/dnaPipeTE/issues/79) for this issue.

Cheers,

Clément

**Comment by zpliu1126** [comment]
Hi， I solved the issue by download Dfam v3.7 
`wget https://www.dfam.org/releases/Dfam_3.7/families/Dfam_curatedonly.h5.gz` 
 and `famdb.py`  from https://github.com/rmhubley/RepeatMasker
