### ISSUE TITLE
Reduce root partition size

### ISSUE THREAD

**Issue by SooLee** [Dfam-consortium/FamDB#7]
Hi it's been taking a long time to download the root famDB partition 0 - it's 8.9 G and that's required to install RepeakMasker which is required to install RepeakModeler, even though I don't actually need any of the famDB. If this is going to be required, please make it really 'minimal', like 10kb or something.

**Comment by SooLee** [comment]
It took 35 min to just download https://www.dfam.org/releases/Dfam_3.8/families/FamDB/dfam38_full.0.h5.gz

**Comment by SooLee** [comment]
It is also 67 GB after unzipping and takes up too much space.

**Comment by asgray** [comment]
RepeatMasker 4.1.7 and TETools 1.89 address this issue.  They come with a minimal famdb file that can be replaced or overwritten by the downloads from dfam.org
