### ISSUE TITLE
Preperation of repeat library fails

### ISSUE THREAD

**Issue by jayramr** [Dfam-consortium/FamDB#8]
Hi, 

I'm generating the repeat library as per this link -> https://github.com/shohei-kojima/MEGAnE/wiki/Prepare-a-custom-repeat-library-and-annotation-(mostly-for-analysis-of-non-human-WGS)#Preparation-of-repeat-library

```
wget https://www.dfam.org/releases/Dfam_3.2/families/Dfam_curatedonly.h5.gz
gzip -d Dfam_curatedonly.h5.gz
python famdb.py -i ./Dfam_curatedonly.h5 families -f embl -ad 8355 > Dfam_custom.embl

ERROR:famdb_globals:A partitioned famdb database is not present in db_custom/
There were several *.h5 files present. However, they do not appear
to be in the correct format: Dfam_curatedonly.h5
```

Please advise

**Comment by asgray** [comment]
Hi Jayaram, what version of FamDB are you using? There was a breaking update with Dfam 3.8 and FamDB 1.0.
Any Dfam version 3.7 or earlier uses a single HDF5 file download and will need to use FamDB 0.4. 
Also, if you're using RepeatMasker, you'll need to use version 4.1.5 or earlier to use older versions of Dfam and FamDB.
Let me know if that helps

**Comment by jayramr** [comment]
Yes this worked, i used the older version solved the problem.
